### ISSUE TITLE
Grid-breaking pull quote not correctly displayed for Safari browser

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-blog#118] opened 2021-04-14 09:55 UTC
Prerequisites:
Safari browser 14.0.3

Steps to reproduce:
1. In Addons blog, open a page containing a grid-breaking pull quote in Safari browser: https://addons-blog-preview-willdurand.vercel.app/blog/2021/03/24/blog-post-lorem-ipsum-001/
2. Observe how the grid-breaking pull quote is displayed

Expected results:
The blockquotes are incorporated in the right side of the text like in following screenshot:
<img width="443" alt="blockquoteexpected" src="https://user-images.githubusercontent.com/1583842/114691577-7e651480-9d20-11eb-8b5b-c240cdf3a206.png">
 

Actual results:
In Safari browser, the blockquotes are inserted in the left side of the page

Please see screenshot for this issue:
<img width="1037" alt="Screen Shot 2021-04-14 at 12 46 30 PM" src="https://user-images.githubusercontent.com/1583842/114691655-92a91180-9d20-11eb-91b6-cb42820e5a85.png">

NOTES:
Not reproducible in Firefox or Chrome

**Comment by willdurand** [comment] 2021-04-14 12:41
Ha, it's not ugly at least!

**Comment by willdurand** [comment] 2021-04-17 13:52
@vcarciu mmm I could not reproduce. What's your screen resolution?

**Comment by willdurand** [comment] 2021-04-29 11:39
I am closing this issue because when the width of the browser is > 1366px, the pull quote should be displayed correctly. Safari does not behave differently here.

**Closed by willdurand** 2021-04-29 11:40 UTC
Labels: component: blog, priority: mvp-polish, priority: p3

**Comment by vcarciu** [comment] 2021-04-29 12:14
Hey, sorry for late response, I missed the notification for this issue. My screen resolution is 1280x800. Please let me know if this is expected at this resolution.

**Comment by willdurand** [comment] 2021-04-29 12:17
> Hey, sorry for late response, I missed the notification for this issue. My screen resolution is 1280x800. Please let me know if this is expected at this resolution.

Yep, at that resolution, there shouldn't be any grid-breaking pull quote.
