### ISSUE TITLE
Disable/hide Wordpress frontend

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#1] opened 2021-03-16 12:26 UTC
The WP frontend is currently not indexable, but we should also prevent anyone from getting to it directly.

<img width="707" alt="WP Site visibility settings" src="https://user-images.githubusercontent.com/1514/111308616-cfff7e00-8652-11eb-9a9d-98ad76a14652.png">

It could be completely hidden as long as the WP instance can still respond to the admin or API calls.

**Comment by muffinresearch** [comment] 2021-03-22 11:29
A solution to this would be to use https://wordpress.org/plugins/headless-mode/

This redirects but, it would be nice to have the option to 403 rather than redir. Maybe they would take a patch? Repo is here: https://github.com/Shelob9/headless-mode

**Comment by willdurand** [comment] 2021-03-24 19:38
@muffinresearch I wrote this plugin: https://github.com/willdurand/wp-amo-headless, it seems to work as intended on our instance.

**Comment by muffinresearch** [comment] 2021-03-25 10:00
Nice, looks good 👍

**Comment by willdurand** [comment] 2021-03-25 10:56
Plugin above transferred to https://github.com/mozilla/addons-wp-headless.

**Closed by willdurand** 2021-03-25 10:56 UTC
Labels: priority: mvp
